networks:
  net:
    driver: bridge

services:
  node:
    build:
      context: ./
      target: node
    container_name: docker_node
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - .:/app
    networks:
      - net

  chromadb:
    image: chromadb_server
    container_name: docker_chromadb
    build:
      context: ./
      dockerfile: ./ChromaDB/Dockerfile
    volumes:
      - ./ChromaDB:/ChromaDB
      - index_data:/index_data
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config log_config.yml
    environment:
      - CHROMA_DB_IMPL=clickhouse
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
    ports:
      - 8000:8000
    depends_on:
      - clickhouse
    networks:
      - net

  clickhouse:
    image: clickhouse/clickhouse-server:22.9-alpine
    container_name: docker_clickhouse
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_TCP_PORT=9000
      - CLICKHOUSE_HTTP_PORT=8123
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
      - backups:/backups
      - ./ChromaDB/config/backup_disk.xml:/etc/clickhouse-server/config.d/backup_disk.xml
      - ./ChromaDB/config/chroma_users.xml:/etc/clickhouse-server/users.d/chroma.xml
    networks:
      - net

volumes:
  clickhouse_data:
    driver: local
  clickhouse_logs:
    driver: local
  index_data:
    driver: local
  backups:
    driver: local
